/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/oauth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Callback
         * @description Handle Google OAuth callback.
         *     Exchanges authorization code for access token and stores it in cookies.
         *     Validates state from cookie to prevent CSRF and login CSRF attacks.
         */
        get: operations["callback_oauth_google_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oauth/google/redirect_url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Redirect Url
         * @description Redirect user to Google OAuth.
         *     Sets oauth_state cookie (first-party on backend domain) for CSRF protection,
         *     then redirects the browser directly to Google's consent page.
         */
        get: operations["redirect_url_oauth_google_redirect_url_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/graph/{graph_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get
         * @description Get graph data by ID, with unacknowledged generation results folded in.
         */
        get: operations["get_graph__graph_id__get"];
        /**
         * Save
         * @description Save the autosaved working graph for the current user.
         *
         *     Unacknowledged generation-job results are folded into the payload first, so
         *     a client holding pre-completion state can never overwrite a server-side
         *     result; records the payload retires (acked or node-deleted) are dropped.
         *
         *     The save is conditional on the payload's revision matching the stored
         *     case (409 otherwise), so a stale client can never overwrite work saved
         *     from another tab or device. A case that is gone answers 404 rather than
         *     being recreated: a save carries a snapshot that can outlive its case, and
         *     storing it would undo a delete. Neither rejection retires anything: job
         *     records outlive the rejected save and are re-delivered when the client
         *     reloads.
         */
        put: operations["save_graph__graph_id__put"];
        post?: never;
        /**
         * Delete
         * @description Delete graph by ID, along with its generation jobs.
         */
        delete: operations["delete_graph__graph_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/graph/{graph_id}/rename": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Rename
         * @description Rename a graph by ID.
         */
        patch: operations["rename_graph__graph_id__rename_patch"];
        trace?: never;
    };
    "/graph/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get All Metadata
         * @description Get metadata for all graphs for user (lightweight listing).
         */
        get: operations["get_all_metadata_graph__get"];
        put?: never;
        /**
         * Create New
         * @description Create a new empty graph for the current user.
         */
        post: operations["create_new_graph__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/graph/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Case
         * @description Create a case from an uploaded export file.
         *
         *     An import creates; it never saves over a case. The id is minted here and
         *     the file carries none, so an import can neither collide with a case in
         *     the account nor put back one the user deleted.
         */
        post: operations["import_case_graph_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/graph/{graph_id}/generate-name": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Name
         * @description Endpoint to generate a name for a graph based on its content.
         */
        post: operations["generate_name_graph__graph_id__generate_name_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange Token
         * @description Exchange a one-time authorization code for access and refresh tokens.
         */
        post: operations["exchange_token_auth_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Access Token
         * @description Refresh access token using refresh token from request body.
         */
        post: operations["refresh_access_token_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current User
         * @description Get current authenticated user info.
         *     Used by frontend to check authentication status.
         */
        get: operations["get_current_user_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/share/graph/{graph_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enable Share
         * @description Enable sharing for a graph. Idempotent.
         */
        post: operations["enable_share_share_graph__graph_id__post"];
        /**
         * Disable Share
         * @description Disable sharing for a graph.
         */
        delete: operations["disable_share_share_graph__graph_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/share/{graph_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Shared Graph
         * @description Get a shared graph by ID. No authentication required.
         *     Returns 404 for both "not found" and "not shared" to prevent enumeration.
         */
        get: operations["get_shared_graph_share__graph_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/share/{graph_id}/copy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Copy Shared Graph
         * @description Copy a shared graph to the authenticated user's account.
         */
        post: operations["copy_shared_graph_share__graph_id__copy_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/research/{graph_id}/node/{node_id}/suggest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Suggest
         * @description Endpoint for transient question suggestions (selection popup, canvas).
         */
        post: operations["suggest_research__graph_id__node__node_id__suggest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/research/{graph_id}/node/{node_id}/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Answer
         * @description Start (or queue) server-owned answer generation for a question node.
         */
        post: operations["generate_answer_research__graph_id__node__node_id__generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/research/{graph_id}/node/{node_id}/suggest-followups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Suggest Followups
         * @description Start a follow-up suggestion generation; results arrive on the job stream.
         */
        post: operations["suggest_followups_research__graph_id__node__node_id__suggest_followups_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/research/{graph_id}/node/{node_id}/cheat-sheet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Cheat Sheet
         * @description Condense the thread above a question on demand: for questions answered
         *     before "summarize parents" was turned on, and to refresh a sheet whose
         *     thread has moved on. The answer flow starts the same job automatically.
         */
        post: operations["generate_cheat_sheet_research__graph_id__node__node_id__cheat_sheet_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/research/{graph_id}/suggest-big-picture": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Suggest Big Picture
         * @description Start a big-picture suggestion generation; results arrive on the job stream.
         */
        post: operations["suggest_big_picture_research__graph_id__suggest_big_picture_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/research/{graph_id}/context-size": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Context Size
         * @description Count the prompt the next question would send, against what its model accepts.
         */
        post: operations["context_size_research__graph_id__context_size_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/research/{graph_id}/stream-ticket": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Stream Ticket
         * @description Hand out the credential the browser will put in the stream URL.
         *
         *     Identity and ownership are established here, on an ordinary authenticated
         *     request whose token travels in a header. What goes into the URL — and from
         *     there into every access log — is only this ticket: one case, half a minute,
         *     no access to anything else.
         */
        post: operations["create_stream_ticket_research__graph_id__stream_ticket_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/research/kickstart/brief": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Brief
         * @description Generate the case brief from the user's kickoff notes.
         */
        post: operations["generate_brief_research_kickstart_brief_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/research/kickstart/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Questions
         * @description Generate starting questions from the kickoff notes and list state.
         */
        post: operations["generate_questions_research_kickstart_questions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/research/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Report
         * @description Generate a Markdown report summarizing the whole case.
         */
        post: operations["generate_report_research_report_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transcription/transcribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Transcribe Audio
         * @description Transcribe a recorded audio clip into text for the kickstart notes.
         */
        post: operations["transcribe_audio_transcription_transcribe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check endpoint.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ContextSizeRequestDTO
         * @description Request body for counting the prompt the next question would send.
         */
        ContextSizeRequestDTO: {
            /** Model */
            model: string;
            /** Parentnodeid */
            parentNodeId?: string | null;
            /**
             * Draftquery
             * @default
             */
            draftQuery: string;
            /**
             * Draftdocuments
             * @default []
             */
            draftDocuments: components["schemas"]["DocumentDTO"][];
        };
        /**
         * ContextSizeResponseDTO
         * @description How big the next question's prompt is, against what its model accepts.
         */
        ContextSizeResponseDTO: {
            /** Tokens */
            tokens: number;
            /** Maxinputtokens */
            maxInputTokens: number;
            /** Estimated */
            estimated: boolean;
        };
        /**
         * DeclinedQuestionDTO
         * @description A suggestion the user explicitly declined; feeds the suggester as an anti-target.
         */
        DeclinedQuestionDTO: {
            /** Text */
            text: string;
            /** Reason */
            reason?: ("know_this" | "too_basic" | "off_topic" | "unclear") | null;
            /** Parentnodeid */
            parentNodeId?: string | null;
            /**
             * Declinedat
             * Format: date-time
             */
            declinedAt: string;
        };
        /**
         * DocumentDTO
         * @description Data Transfer Object for document information.
         *
         *     This class represents a document with its basic properties including
         *     a unique identifier, display name, type, and content.
         *     For txt documents, content is raw text.
         *     For pdf documents, content is base64-encoded PDF data.
         */
        DocumentDTO: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Type
             * @enum {string}
             */
            type: "txt" | "pdf";
            /** Content */
            content: string;
        };
        /**
         * EdgeDTO
         * @description A directed edge in the question graph: source is the parent question,
         *     target the follow-up filed under it.
         */
        EdgeDTO: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Source
             * Format: uuid
             */
            source: string;
            /**
             * Target
             * Format: uuid
             */
            target: string;
        };
        /**
         * ExecutionDTO
         * @description How an agent CLI answer was produced: the provider (claude_code, hermes),
         *     the model it reported, and notes on what it could not use. Shown beside
         *     the answer; never fed back into any prompt. Absent on API-key answers and
         *     on answers from before it was recorded.
         */
        ExecutionDTO: {
            /** Provider */
            provider: string;
            /** Model */
            model?: string | null;
            /**
             * Notes
             * @default []
             */
            notes: string[];
        };
        /**
         * GenerateAnswerRequestDTO
         * @description Request body to start (or queue) an answer generation for a question node.
         */
        GenerateAnswerRequestDTO: {
            /**
             * Background
             * @default false
             */
            background: boolean;
            /**
             * Websearchenabled
             * @default true
             */
            webSearchEnabled: boolean;
            /**
             * Verbosity
             * @default low
             * @enum {string}
             */
            verbosity: "low" | "medium";
            /**
             * Cheatsheet
             * @default false
             */
            cheatSheet: boolean;
            /**
             * Force
             * @default false
             */
            force: boolean;
        };
        /**
         * GraphNoId
         * @description DTO for graph data without ID.
         */
        GraphNoId: {
            /** Nodes */
            nodes: components["schemas"]["NodeDTO"][];
            /** Edges */
            edges: components["schemas"]["EdgeDTO"][];
            /** Nodecontents */
            nodeContents: components["schemas"]["NodeContentDTO"][];
            /**
             * Brief
             * @default
             */
            brief: string;
            /**
             * Casedocuments
             * @default []
             */
            caseDocuments: components["schemas"]["DocumentDTO"][];
            /**
             * Suggestions
             * @default []
             */
            suggestions: components["schemas"]["ResearchSuggestionDTO"][];
            /**
             * Declinedquestions
             * @default []
             */
            declinedQuestions: components["schemas"]["DeclinedQuestionDTO"][];
            /**
             * Readhistory
             * @default []
             */
            readHistory: components["schemas"]["ReadEventDTO"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HighlightDTO
         * @description A passage the user marked as an insight (the lightbulb action in the
         *     selection popup). Anchored to the answer text like a selection; carries no
         *     child question. Strong positive signal of what the user found important —
         *     fed to the answerer, the suggesters, and the report.
         */
        HighlightDTO: {
            /** Id */
            id: string;
            /** Text */
            text: string;
            /** Startoffset */
            startOffset?: number | null;
            /** Endoffset */
            endOffset?: number | null;
            /** Prefix */
            prefix?: string | null;
            /** Suffix */
            suffix?: string | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
        };
        /**
         * ImportGraphDTO
         * @description DTO for creating a case from an uploaded export file.
         *
         *     The file's own id and revision are deliberately absent: an import is a
         *     create, and the server mints both.
         */
        ImportGraphDTO: {
            /** Nodes */
            nodes: components["schemas"]["NodeDTO"][];
            /** Edges */
            edges: components["schemas"]["EdgeDTO"][];
            /** Nodecontents */
            nodeContents: components["schemas"]["NodeContentDTO"][];
            /**
             * Brief
             * @default
             */
            brief: string;
            /**
             * Casedocuments
             * @default []
             */
            caseDocuments: components["schemas"]["DocumentDTO"][];
            /**
             * Suggestions
             * @default []
             */
            suggestions: components["schemas"]["ResearchSuggestionDTO"][];
            /**
             * Declinedquestions
             * @default []
             */
            declinedQuestions: components["schemas"]["DeclinedQuestionDTO"][];
            /**
             * Readhistory
             * @default []
             */
            readHistory: components["schemas"]["ReadEventDTO"][];
            /** Name */
            name: string;
        };
        /**
         * JobDTO
         * @description A generation job with its effective status and any terminal payload.
         */
        JobDTO: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "answer" | "suggestions" | "big_picture" | "cheat_sheet";
            /** Nodeid */
            nodeId: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "done" | "error";
            /** Answer */
            answer?: string | null;
            /** Answeredat */
            answeredAt?: string | null;
            /**
             * Sources
             * @default []
             */
            sources: components["schemas"]["WebSourceDTO"][];
            /**
             * Sourcesfound
             * @default 0
             */
            sourcesFound: number;
            execution?: components["schemas"]["ExecutionDTO"] | null;
            /**
             * Suggestions
             * @default []
             */
            suggestions: components["schemas"]["ResearchSuggestionDTO"][];
            /** Error */
            error?: string | null;
        };
        /**
         * KickstartBriefRequestDTO
         * @description Request body for generating a case brief from kickoff notes.
         */
        KickstartBriefRequestDTO: {
            /** Inputtext */
            inputText: string;
            /**
             * Documents
             * @default []
             */
            documents: components["schemas"]["DocumentDTO"][];
        };
        /**
         * KickstartBriefResponseDTO
         * @description Response body with the generated case brief.
         */
        KickstartBriefResponseDTO: {
            /** Brief */
            brief: string;
        };
        /**
         * KickstartDeclinedQuestionDTO
         * @description A kickoff question the user declined, with the reason when they gave one.
         */
        KickstartDeclinedQuestionDTO: {
            /** Text */
            text: string;
            /** Reason */
            reason?: ("know_this" | "too_basic" | "off_topic" | "unclear") | null;
        };
        /**
         * KickstartQuestionDTO
         * @description One proposed starting question; from_user marks questions extracted from the notes.
         */
        KickstartQuestionDTO: {
            /** Text */
            text: string;
            /** Fromuser */
            fromUser: boolean;
        };
        /**
         * KickstartQuestionsRequestDTO
         * @description Request body for generating starting questions from kickoff notes.
         */
        KickstartQuestionsRequestDTO: {
            /** Inputtext */
            inputText: string;
            /**
             * Documents
             * @default []
             */
            documents: components["schemas"]["DocumentDTO"][];
            /**
             * Brief
             * @default
             */
            brief: string;
            /**
             * Approved
             * @default []
             */
            approved: string[];
            /**
             * Pending
             * @default []
             */
            pending: string[];
            /**
             * Declined
             * @default []
             */
            declined: components["schemas"]["KickstartDeclinedQuestionDTO"][];
            /**
             * Requestmore
             * @default false
             */
            requestMore: boolean;
        };
        /**
         * KickstartQuestionsResponseDTO
         * @description Response body with proposed starting questions.
         */
        KickstartQuestionsResponseDTO: {
            /** Questions */
            questions: components["schemas"]["KickstartQuestionDTO"][];
        };
        /**
         * NodeContentDTO
         * @description Data Transfer Object for node content in the graph system.
         *
         *     Represents the complete content and metadata of a node, including the user's query,
         *     AI-generated response, associated documents, and various selections made by the user.
         */
        NodeContentDTO: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Query */
            query: string;
            /** Response */
            response: string;
            /** Selectedmodel */
            selectedModel: string;
            /** Documents */
            documents: components["schemas"]["DocumentDTO"][];
            /** Answeredat */
            answeredAt?: string | null;
            /** Resolvedat */
            resolvedAt?: string | null;
            /** Lovedat */
            lovedAt?: string | null;
            /** Parentselectedtext */
            parentSelectedText?: string | null;
            /** Parentselectedprefix */
            parentSelectedPrefix?: string | null;
            /** Parentselectedsuffix */
            parentSelectedSuffix?: string | null;
            /** Selectionsuggestions */
            selectionSuggestions: string[];
            /** Selections */
            selections: components["schemas"]["TextSelectionDTO"][];
            /**
             * Highlights
             * @default []
             */
            highlights: components["schemas"]["HighlightDTO"][];
            /** Cheatsheet */
            cheatSheet?: string | null;
            /**
             * Sources
             * @default []
             */
            sources: components["schemas"]["WebSourceDTO"][];
            /**
             * Sourcesfound
             * @default 0
             */
            sourcesFound: number;
            execution?: components["schemas"]["ExecutionDTO"] | null;
        };
        /**
         * NodeDTO
         * @description A question node. All business data lives in NodeContentDTO under the same id.
         */
        NodeDTO: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /**
         * ReadEventDTO
         * @description A first-read event: the user has read the answer of the given node.
         */
        ReadEventDTO: {
            /**
             * Nodeid
             * Format: uuid
             */
            nodeId: string;
            /**
             * At
             * Format: date-time
             */
            at: string;
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /**
         * RenameGraphDTO
         * @description DTO for renaming a graph.
         */
        RenameGraphDTO: {
            /** Name */
            name: string;
        };
        /**
         * ReportRequestDTO
         * @description Request body for generating a Markdown report of the whole case.
         */
        ReportRequestDTO: {
            graph: components["schemas"]["GraphNoId"];
            /**
             * Guidance
             * @default
             */
            guidance: string;
        };
        /**
         * ReportResponseDTO
         * @description Response body with the generated Markdown report.
         */
        ReportResponseDTO: {
            /** Markdown */
            markdown: string;
        };
        /**
         * ResearchSuggestRequestDTO
         * @description Request body for transient question suggestions (selection popup, canvas).
         */
        ResearchSuggestRequestDTO: {
            graph: components["schemas"]["GraphNoId"];
            selection?: components["schemas"]["SelectionDTO"] | null;
        };
        /**
         * ResearchSuggestResponseDTO
         * @description Response body for research question suggestions.
         */
        ResearchSuggestResponseDTO: {
            /** Questions */
            questions: string[];
        };
        /**
         * ResearchSuggestionDTO
         * @description A question proposed by the system, awaiting user accept/decline in the research view.
         *
         *     Pending under its parent question until accepted or declined — no lifespan.
         */
        ResearchSuggestionDTO: {
            /** Id */
            id: string;
            /**
             * Parentnodeid
             * Format: uuid
             */
            parentNodeId: string;
            /** Text */
            text: string;
            /**
             * Bigpicture
             * @default false
             */
            bigPicture: boolean;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
        };
        /**
         * SaveGraphDataNoIdDTO
         * @description DTO for graph data.
         */
        SaveGraphDataNoIdDTO: {
            /** Nodes */
            nodes: components["schemas"]["NodeDTO"][];
            /** Edges */
            edges: components["schemas"]["EdgeDTO"][];
            /** Nodecontents */
            nodeContents: components["schemas"]["NodeContentDTO"][];
            /**
             * Brief
             * @default
             */
            brief: string;
            /**
             * Casedocuments
             * @default []
             */
            caseDocuments: components["schemas"]["DocumentDTO"][];
            /**
             * Suggestions
             * @default []
             */
            suggestions: components["schemas"]["ResearchSuggestionDTO"][];
            /**
             * Declinedquestions
             * @default []
             */
            declinedQuestions: components["schemas"]["DeclinedQuestionDTO"][];
            /**
             * Readhistory
             * @default []
             */
            readHistory: components["schemas"]["ReadEventDTO"][];
            /** Name */
            name: string;
            /** Createdat */
            createdAt?: string | null;
            /**
             * Revision
             * @default 0
             */
            revision: number;
            /**
             * Ackedjobids
             * @default []
             */
            ackedJobIds: string[];
        };
        /**
         * SelectionDTO
         * @description A passage the user selected in the current question's answer.
         */
        SelectionDTO: {
            /** Text */
            text: string;
            /** Prefix */
            prefix?: string | null;
            /** Suffix */
            suffix?: string | null;
        };
        /**
         * StreamTicketDTO
         * @description A short-lived credential for opening one case's job event stream.
         */
        StreamTicketDTO: {
            /** Ticket */
            ticket: string;
        };
        /**
         * SuggestFollowupsRequestDTO
         * @description Request body to start a follow-up suggestion generation.
         */
        SuggestFollowupsRequestDTO: {
            /**
             * Requestmore
             * @default false
             */
            requestMore: boolean;
        };
        /**
         * TextSelectionDTO
         * @description Data Transfer Object for representing a text selection within a document.
         */
        TextSelectionDTO: {
            /** Text */
            text: string;
            /** Startoffset */
            startOffset?: number | null;
            /** Endoffset */
            endOffset?: number | null;
            /** Prefix */
            prefix?: string | null;
            /** Suffix */
            suffix?: string | null;
            /** Childnodeid */
            childNodeId?: string | null;
        };
        /** TokenExchangeRequest */
        TokenExchangeRequest: {
            /** Code */
            code: string;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /**
         * TranscribeRequestDTO
         * @description Request body for transcribing a recorded audio clip.
         */
        TranscribeRequestDTO: {
            /** Audio */
            audio: string;
            /** Mimetype */
            mimeType: string;
        };
        /**
         * TranscribeResponseDTO
         * @description Response body with the transcribed text.
         */
        TranscribeResponseDTO: {
            /** Text */
            text: string;
        };
        /**
         * User
         * @description Domain model for User entity.
         */
        User: {
            /** Id */
            id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Name */
            name?: string | null;
            /** Picture */
            picture?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WebSourceDTO
         * @description One page a web search put in front of the model while it wrote an answer.
         *
         *     cited marks the ones the answer draws on — those are already linked inline
         *     in the text; the rest are what the model looked at and passed over. Only
         *     Claude titles every result, so a bare URL is normal.
         */
        WebSourceDTO: {
            /** Url */
            url: string;
            /** Title */
            title?: string | null;
            /** Pageage */
            pageAge?: string | null;
            /**
             * Cited
             * @default false
             */
            cited: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    callback_oauth_google_callback_get: {
        parameters: {
            query: {
                code?: string | null;
                state: string;
                scope?: string | null;
                authuser?: number | null;
                prompt?: string | null;
                error?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                oauth_state?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    redirect_url_oauth_google_redirect_url_get: {
        parameters: {
            query: {
                /** @description URL to redirect to after OAuth flow */
                next_url: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_graph__graph_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                graph_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_graph__graph_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                graph_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveGraphDataNoIdDTO"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_graph__graph_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                graph_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_graph__graph_id__rename_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                graph_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameGraphDTO"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_all_metadata_graph__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    create_new_graph__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    import_case_graph_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportGraphDTO"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_name_graph__graph_id__generate_name_post: {
        parameters: {
            query?: never;
            header?: {
                "x-openai-api-key"?: string | null;
            };
            path: {
                graph_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    exchange_token_auth_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenExchangeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_access_token_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_user_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    enable_share_share_graph__graph_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                graph_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disable_share_share_graph__graph_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                graph_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_shared_graph_share__graph_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                graph_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    copy_shared_graph_share__graph_id__copy_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                graph_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    suggest_research__graph_id__node__node_id__suggest_post: {
        parameters: {
            query?: never;
            header?: {
                "x-openai-api-key"?: string | null;
            };
            path: {
                node_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResearchSuggestRequestDTO"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchSuggestResponseDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_answer_research__graph_id__node__node_id__generate_post: {
        parameters: {
            query?: never;
            header?: {
                "x-openai-api-key"?: string | null;
                "x-anthropic-api-key"?: string | null;
            };
            path: {
                graph_id: string;
                node_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateAnswerRequestDTO"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    suggest_followups_research__graph_id__node__node_id__suggest_followups_post: {
        parameters: {
            query?: never;
            header?: {
                "x-openai-api-key"?: string | null;
            };
            path: {
                graph_id: string;
                node_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SuggestFollowupsRequestDTO"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_cheat_sheet_research__graph_id__node__node_id__cheat_sheet_post: {
        parameters: {
            query?: never;
            header?: {
                "x-openai-api-key"?: string | null;
            };
            path: {
                graph_id: string;
                node_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    suggest_big_picture_research__graph_id__suggest_big_picture_post: {
        parameters: {
            query?: never;
            header?: {
                "x-openai-api-key"?: string | null;
            };
            path: {
                graph_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    context_size_research__graph_id__context_size_post: {
        parameters: {
            query?: never;
            header?: {
                "x-openai-api-key"?: string | null;
                "x-anthropic-api-key"?: string | null;
            };
            path: {
                graph_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContextSizeRequestDTO"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContextSizeResponseDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_stream_ticket_research__graph_id__stream_ticket_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                graph_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamTicketDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_brief_research_kickstart_brief_post: {
        parameters: {
            query?: never;
            header?: {
                "x-openai-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KickstartBriefRequestDTO"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KickstartBriefResponseDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_questions_research_kickstart_questions_post: {
        parameters: {
            query?: never;
            header?: {
                "x-openai-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KickstartQuestionsRequestDTO"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KickstartQuestionsResponseDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_report_research_report_post: {
        parameters: {
            query?: never;
            header?: {
                "x-openai-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportRequestDTO"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportResponseDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transcribe_audio_transcription_transcribe_post: {
        parameters: {
            query?: never;
            header?: {
                "x-openai-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TranscribeRequestDTO"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscribeResponseDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
